apiVersion: v1
kind: Service
metadata:
    name: backend-deployment-test-service
spec:
    ports:
        - name: http
          port: 3001
          protocol: TCP
          targetPort: 3001
    selector:
        app: backend-deployment-test
