apiVersion: v1
kind: Service
metadata:
    name: backend-deployment-test-service
spec:
    ports:
        - name: http
          port: "${PORT}"
          protocol: TCP
          targetPort: "${PORT}"
    selector:
        app: backend-deployment-test
