apiVersion: v1
kind: Service
metadata:
    name: backend-deployment-test-service
spec:
    selector:
        app: backend-deployment-test
    type: NodePort
    ports:
       - protocol: TCP
         port: 80
         targetPort: 3001
         nodePort: 32578
