apiVersion: v1
kind: Service
metadata:
    name: backend-deployment-test-service
spec:
    type: NodePort
    ports:
       - protocol: TCP
         port: 80
         targetPort: 3001
    type: ClusterIP
