apiVersion: v1
kind: Service
metadata:
    name: backend-deployment-test-service
spec:
    ports:
        - protocol: TCP
          port: 3001
          targetPort: 3001
    selector:
        app: backend-deployment-test
