apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment-test
  template:
    metadata:
      labels:
        app: backend-deployment-test
    spec:
      containers:
        - name: backend-deployment-test
          image: <IMAGE_TAG>
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config