apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment-test
  template:
    metadata:
      labels:
        app: backend-deployment-test
    spec:
      containers:
        - name: backend-deployment-test
          image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_TAG}"
          ports:
            - containerPort: "${PORT}"
          envFrom:
            - configMapRef:
                name: backend-config