apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-deployment-test
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 2
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: backend-deployment-test
    spec:
      containers:
        - name: backend-deployment-test
          image: <IMAGE_TAG>
          imagePullPolicy: IfNotPresent
          ports:
              - containerPort: 3001
          envFrom:
            - configMapRef:
                name: backend-config